### ISSUE TITLE
How to build weakSAM proposals?

### ISSUE THREAD

**Issue by Hwang64** [hustvl/WeakSAM#1]
The output of the SAM is the masks of the objects, so how to obtain the proposals from the weakSAM? It is not mentioned in the paper.

**Comment by Colezwhy** [comment]
> The output of the SAM is the masks of the objects, so how to obtain the proposals from the weakSAM? It is not mentioned in the paper.

Hi, sorry for late reply. 
We simply take the bounding rectangle of masks as the proposal boxes of our WeakSAM proposal.
